- name: Install npm
  apt: name=npm state=present
  tags: js-env

- name: Install bower and ember-cli package globally.
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - ember-cli
  tags: js-env

- name: Install postgres
  apt: name=postgresql state=present

- name: Install postgres dev lib for builing pg gem
  apt: name=libpq-dev state=present
