- hosts: all
  remote_user: deploy
  sudo: true

  roles:
    - { role: common_deploy_user }
    - { role: common_packages }
    - { role: geerlingguy.ruby, ruby_install_from_source: true, ruby_download_url: 'http://ftp.ruby-lang.org/pub/ruby/ruby-2.4.1.tar.gz', ruby_version: '2.4.1' }
    - { role: nginx_passenger, mina_deploy: true }
    - { role: geerlingguy.redis }

  tasks:
    - name: Deploy user standard setup
      include_role:
        name: user_standard_setup
      with_items:
        - deploy
