- name: Create git directory 1_of_2
  file:
    path: /opt
    state: directory
    mode: 0755
  tags: git

- name: Create git directory 2_of_2
  file:
    path: '/opt/git'
    state: directory
    owner: deploy
    group: deploy
    mode: 0755
  tags: git

