---
- name: Create deploy user
  include: create_deploy_user.yml

- name: Enable passwordless sudo
  include: enable_passwordless_sudo.yml

- name: Set deploy as owner of /var/www
  include: set_deploy_as_owner_of_var_www.yml

- name: Directory for git usage
  include: directory_for_git_usage.yml

- name: Add github to known hosts
  include: add_github_to_known_hosts.yml
